In [1]:
import pandas as pd
import numpy as np


In [2]:
# 데이터를 분석하려면 데이터 프레임 형태로 만들면 됨.
# 행(인스턴스, 실제값), 열(속성, 특성)을 가지는 2차원이 되게 됨.
# 파이썬에서는 데이터분석시 사용하는 2차원을 다루기 위해서 클래스(부품)을 만들었음.

# 데이터프레임을 만드는 방법
***
* dic사용
* csv, excel파일 읽어오기
* df에 values, column을 지정

# dic사용하기

In [46]:
dics = {"name" : ["홍길동","박길동","김길동","송길동"], "age" : [10,20,30,40]}
df = pd.DataFrame(dics)
df

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

In [63]:
# enumerate 연습

for i, item in enumerate(df['name'],1):
     print(i," : ", item, '님')

1  :  홍길동 님
2  :  박길동 님
3  :  김길동 님
4  :  송길동 님


In [52]:
# 인덱스가 자동증가해서 붙어있는 부품 : 데이터프레임
df.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
type(df.index)  #Rangeindex의 부품. class!


pandas.core.indexes.range.RangeIndex

In [9]:
df_index = df.index.tolist()  # 인덱스만 목록으로 가지고 오고 싶으면 tolist를 사용해라!!
df_index

[0, 1, 2, 3]

In [6]:
df['name']

0    홍길동
1    박길동
2    김길동
3    송길동
Name: name, dtype: object

In [7]:
type(df['name'])  # 데이터프레임안에서 인덱스를 뺀 나머지 열은 시리즈.

pandas.core.series.Series

In [10]:
# 데이터프레임은 RangeIndex, Series의 결합임

## Series란?
인덱스와 array객체가 결합된 형태

In [11]:
df['name'].index

RangeIndex(start=0, stop=4, step=1)

In [26]:
type(df['name'].index)

pandas.core.indexes.range.RangeIndex

In [12]:
df_name_list = df['name'].index.tolist()
df_name_list

[0, 1, 2, 3]

In [13]:
df['name'].values

array(['홍길동', '박길동', '김길동', '송길동'], dtype=object)

In [16]:
type(df['name'].values)

numpy.ndarray

In [18]:
df_name_values = df['name'].values.tolist()
df_name_values

['홍길동', '박길동', '김길동', '송길동']

In [19]:
type(df_name_values)

list

In [20]:
# Series를 리스트로 바로 변환, 인덱스를 생략한 형태의 리스트가 됨.
df_name_values2 = df['name'].tolist()
df_name_values2

['홍길동', '박길동', '김길동', '송길동']

In [21]:
type(df['name'])

pandas.core.series.Series

In [25]:
# 시리즈를 데이터프레임으로 변경할 수도 있다.
df_name = df['name'].to_frame()
df_name
type(df_name)

pandas.core.frame.DataFrame

# df에 values, column을 지정하는 방법

In [23]:
df2 = pd.DataFrame(data = [['홍길동',100],['김길동', 200]], columns = ['name','age'])
df2

name  age
0  홍길동  100
1  김길동  200

In [24]:
name_values = ["홍길동","박길동","김길동","송길동"]
age_values = [10,20,30,40]

df3 = pd.DataFrame({"name" : name_values, "age" : age_values})
df3

name  age
0  홍길동   10
1  박길동   20
2  김길동   30
3  송길동   40

# 다차원 행렬

In [27]:
data = [100,200,300] # 1차원 리스트
sum(data)

600

In [28]:
max(data)

300

In [35]:
# ndarray : 다양한 차원의 데이터(배열)를 하나의 클래스로 다루기위해서 만들어졌음.
# n : 숫자
# d : dimention, 차원
# array : 배열

In [31]:
arr1 = np.arange(15) # 0~14까지의 연속된 값을 만들어주는 함수,1차원
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr1_reshape = arr1.reshape(3, 5) #원하는 차원(모양)으로 변환해주는 함수 = reshape
arr1_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [34]:
type(arr1_reshape)

numpy.ndarray

In [37]:
# mask
mask = np.zeros(5)
mask

array([0., 0., 0., 0., 0.])

In [38]:
mask2 = np.zeros((3,4))
mask2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
arr2 = np.array([
    [1,2,3],[4,5,6]
    ] ,dtype=np.float64)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]])

In [40]:
arr3 = np.array([
    [7,8,9],[10,11,12]
    ] ,dtype=np.float64)
arr3

array([[ 7.,  8.,  9.],
       [10., 11., 12.]])

In [41]:
# 행렬의 연산을 할 수 있음. 사칙연산 모두 가능!
arr2+arr3

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [42]:
arr2*arr3

array([[ 7., 16., 27.],
       [40., 55., 72.]])

In [43]:
np.random.rand(20)  #랜덤값 20개를 가져옴

array([0.25841264, 0.68046037, 0.14134317, 0.55646035, 0.14599182,
       0.94449574, 0.70282145, 0.29417977, 0.60801656, 0.2217153 ,
       0.04008775, 0.86979361, 0.14777892, 0.11738069, 0.74357712,
       0.97207488, 0.16999725, 0.98424131, 0.32430976, 0.70286096])

In [45]:
np.random.randint(10) # 10이하의 랜덤 int 하나를 가져옴

2